// This file is auto-generated by `npm run generate-types --workspace=@ropero/supabase`
// Run `supabase start` first, then regenerate after applying migrations

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      items: {
        Row: {
          id: string
          user_id: string
          name: string
          brand: string | null
          category: string
          subcategory: string | null
          color_primary: string
          color_secondary: string | null
          pattern: string | null
          size: string | null
          material: string | null
          season: string[]
          formality: number
          photo_urls: string[]
          purchase_date: string | null
          purchase_price: number | null
          purchase_source: string | null
          receipt_email_id: string | null
          times_worn: number
          last_worn_at: string | null
          status: string
          notes: string | null
          tags: string[]
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['items']['Row'], 'id' | 'created_at' | 'updated_at' | 'times_worn'> & {
          id?: string
          created_at?: string
          updated_at?: string
          times_worn?: number
        }
        Update: Partial<Database['public']['Tables']['items']['Insert']>
      }
      outfits: {
        Row: {
          id: string
          user_id: string
          name: string
          occasion: string | null
          photo_url: string | null
          rating: number | null
          notes: string | null
          tags: string[]
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['outfits']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['outfits']['Insert']>
      }
      outfit_items: {
        Row: {
          outfit_id: string
          item_id: string
        }
        Insert: Database['public']['Tables']['outfit_items']['Row']
        Update: Partial<Database['public']['Tables']['outfit_items']['Row']>
      }
      trips: {
        Row: {
          id: string
          user_id: string
          name: string
          destination: string
          start_date: string
          end_date: string
          trip_type: string
          weather_forecast: Json | null
          notes: string | null
          tags: string[]
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['trips']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['trips']['Insert']>
      }
      packing_lists: {
        Row: {
          id: string
          trip_id: string
          user_id: string
          status: string
          notes: string | null
          tags: string[]
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['packing_lists']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['packing_lists']['Insert']>
      }
      packing_list_items: {
        Row: {
          packing_list_id: string
          item_id: string
          packed: boolean
        }
        Insert: Database['public']['Tables']['packing_list_items']['Row']
        Update: Partial<Database['public']['Tables']['packing_list_items']['Row']>
      }
      packing_list_outfits: {
        Row: {
          packing_list_id: string
          outfit_id: string
        }
        Insert: Database['public']['Tables']['packing_list_outfits']['Row']
        Update: Partial<Database['public']['Tables']['packing_list_outfits']['Row']>
      }
      wear_logs: {
        Row: {
          id: string
          user_id: string
          item_id: string
          outfit_id: string | null
          worn_at: string
          occasion: string | null
          weather_conditions: string | null
          notes: string | null
          tags: string[]
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['wear_logs']['Row'], 'id' | 'created_at'> & {
          id?: string
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['wear_logs']['Insert']>
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}
